TC_05.001.008.001
RedRoverSchool/BookClubQA_Python_2024_fall pull request #300
Opened 2024-12-19 19:33 UTC by yuliyafil22

2024-12-19 20:21 UTC, KatyaMy commented
> _ No description provided. _

Ссылку на карточку

2024-12-20 04:01 UTC, yuliyafil22 commented
https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/296

2024-12-20 15:59 UTC, BonumTellurian commented
1) "Кликаем кнопку 'Подробнее' на первой карточке учителя"
могу ошибаться, но - http://testing.misleplav.ru/listings/1/ ведёт не на первую карточку учителя, а на карточку первого учителя.
Если удалим первого учителя - тест скорее всего упадёт

2024-12-20 18:17 UTC, yuliyafil22 commented
а как тогда поступить? не могу понять.

2024-12-21 13:25 UTC, tereshenkov29 commented
> а как тогда поступить? 

На странице со списком объявлений собрать все ссылки на объявления в список
например, вот такой Xpath находит 10 ссылок - `//div[@class="card-body"]/a`

а дальше могут быть разные варианты

первый самый очевидный - если длина списка больше 0 (т.е. есть объявления) - кликнуть по нулевому элементу списка (т.е. по первому объявления)

второй - если длина списка больше 0 - идти по списку циклом, начиная от 1 и проверять, есть ли на странице ссылка `//a[@href="/listings/" + i + "/"]` (где i - переменная цикла)
если есть - кликать на ссылку и завершать цикл
другими словами - нашли ссылку `//a[@href="/listings/1/"]` - кликаем, не нашли - идем дальше проверять ссылку `//a[@href="/listings/2/"]` и т.д. пока не кликнем

2024-12-21 13:27 UTC, tereshenkov29 commented on components/teacher_profile.py
> +first_profile_page = "http://testing.misleplav.ru/listings/1/"
учитывая, что страницу именно с этим ID объявления могут удалить - не очень удачная переменная
можно сделать по-другому

2024-12-21 13:31 UTC, tereshenkov29 requested changes

2024-12-21 13:31 UTC, tereshenkov29 commented on components/teacher_profile.py
> +        expect(self.page).to_have_url(first_profile_page)
нет гарантий, что объявление с ID = 1 всегда будет первой карточкой на странице

2024-12-21 13:31 UTC, tereshenkov29 commented on components/teacher_profile.py
> +class TeacherProfile:
TeacherProfile - действия функции (клик по кнопке) выполняются не на странице профиля
фактически сейчас страница (компонент) профиля в коде никак не используется - страница профиля не проверяется, а проверяется URL

2024-12-23 05:05 UTC, yuliyafil22 commented
Яков, я переделала тест. Посмотри эту идею плиз.

2024-12-25 06:14 UTC, merged